name: Auto commit

on:
  push:
    branches:
      - master

  schedule:
    - cron: '*/3 * * * *' # Runs every 30 seconds

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Modify last update
        run: |
          echo $(date '+%Y-%m-%dT%H:%M:%SZ') > LAST_UPDATED

      - name: Commit changes
        run: |
          git config --local user.email "pkkewat367@gmail.com"
          git config --local user.name "pk367"
          git add -A
          git diff --cached --exit-code || exit 0  # Exit if there are no changes to commit
          git commit -m "chore: auto commit - $(date '+%Y-%m-%d %H:%M:%S')"

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.AUTOCOMMITGITHUB_TOKEN }}
